spring.application.name=backend
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: root
    password: your_password
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: secret_key_123
  expiration: 86400000

logging:
  level:
    org.springframework: INFO
    com.ecommerce.backend: DEBUG